#!/usr/bin/env python3
"""Bootstrap Confidence Intervals for the ReID Discrimination Metrics
=======================================================================
Addresses Reviewer 2, Major Comment #3 (and Minor #10 sensitivity spirit):
"No confidence intervals, bootstrap estimates, or significance tests are
reported for any of the headline numbers (ROC AUC 0.943 vs 0.890, etc.)
Given N=16 for the open-set identities, I'd ask the authors to at least
bootstrap CIs on the discrimination metrics."

This script does NOT need TensorFlow, a GPU, or Colab. It only needs the
already-saved pairwise cosine-similarity scores produced by
feat_vectest_exhaustive_v2.py, which are sitting in this repo at:

    embruns/v5_final/evaluation_results_v2.npz      (proposed V5 model)
    embruns/mars_final/evaluation_results_v2.npz    (mars-small128 baseline)

Both files contain `positive_scores` (535,) and `negative_scores` (600,)
arrays — the exact 535 positive / 600 negative pairs reported in Table 3.
Since both files were generated by the same deterministic pair-sampling
protocol (same manifest, same default --seed 42, and pair generation in
feat_vectest_exhaustive_v2.py depends only on identity structure, not on
the model), positive_scores[i] in one file and positive_scores[i] in the
other correspond to the SAME image pair. That lets us do a *paired*
bootstrap for the V5-vs-baseline delta (tighter, more valid CI than
treating the two models as independent samples), in addition to the
per-model marginal CIs.

Usage
-----
python scripts/bootstrap_ci.py \\
    --v5_npz   embruns/v5_final/evaluation_results_v2.npz \\
    --base_npz embruns/mars_final/evaluation_results_v2.npz \\
    --n_boot   10000 --seed 42

Output: printed table of point estimate + 95% percentile CI for each model,
plus the paired-bootstrap CI on the V5-minus-baseline delta. Also writes a
CSV to --output_csv for direct inclusion in the rebuttal / paper appendix.

Notes on validity
------------------
* Recomputing the "optimal threshold" (Youden's J) inside every bootstrap
  resample means accuracy/F1/precision/recall CIs reflect operating-point
  variability, not just fixed-threshold sampling noise. This matches how
  the original metrics were computed (compute_metrics() in
  feat_vectest_exhaustive_v2.py re-derives the threshold from the data).
* If the two npz files do NOT have matching (pos_n, neg_n) pair counts,
  the script falls back to an unpaired (independent-samples) bootstrap
  for the delta and prints a warning — check that both were produced by
  the same manifest/seed before trusting the paired CI.
"""
from __future__ import annotations

import argparse
import csv
from pathlib import Path
from typing import Dict, Tuple

import numpy as np
from sklearn.metrics import auc, precision_recall_curve, roc_curve


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(
        description="Bootstrap CIs for ReID discrimination metrics",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    p.add_argument("--v5_npz", default="embruns/v5_final/evaluation_results_v2.npz",
                   help="Proposed model's saved pairwise-score .npz.")
    p.add_argument("--base_npz", default="embruns/mars_final/evaluation_results_v2.npz",
                   help="Baseline (mars-small128) saved pairwise-score .npz.")
    p.add_argument("--n_boot", type=int, default=10000,
                   help="Number of bootstrap resamples.")
    p.add_argument("--ci", type=float, default=95.0,
                   help="Confidence level in percent (e.g. 95 -> [2.5, 97.5] percentiles).")
    p.add_argument("--seed", type=int, default=42)
    p.add_argument("--output_csv", default="bootstrap_ci_results.csv",
                   help="Where to write the summary table as CSV.")
    return p.parse_args()


# ---------------------------------------------------------------------------
# Metric computation (mirrors feat_vectest_exhaustive_v2.compute_metrics)
# ---------------------------------------------------------------------------

def compute_point_metrics(pos: np.ndarray, neg: np.ndarray) -> Dict[str, float]:
    y_true = np.concatenate([np.ones(len(pos)), np.zeros(len(neg))])
    y_score = np.concatenate([pos, neg])

    fpr, tpr, thresholds = roc_curve(y_true, y_score)
    roc_auc = auc(fpr, tpr)

    j = tpr - fpr
    opt_idx = int(np.argmax(j))
    opt_thr = float(thresholds[opt_idx])

    precision_arr, recall_arr, _ = precision_recall_curve(y_true, y_score)
    pr_auc = auc(recall_arr, precision_arr)

    preds = (y_score > opt_thr).astype(int)
    accuracy = float(np.mean(preds == y_true))

    tp = int(np.sum((preds == 1) & (y_true == 1)))
    fp = int(np.sum((preds == 1) & (y_true == 0)))
    fn = int(np.sum((preds == 0) & (y_true == 1)))
    prec = tp / (tp + fp) if (tp + fp) > 0 else 0.0
    rec = tp / (tp + fn) if (tp + fn) > 0 else 0.0
    f1 = 2 * prec * rec / (prec + rec) if (prec + rec) > 0 else 0.0

    pos_mean, pos_std = float(np.mean(pos)), float(np.std(pos))
    neg_mean, neg_std = float(np.mean(neg)), float(np.std(neg))
    separation = pos_mean - neg_mean
    denom = np.sqrt(pos_std ** 2 + neg_std ** 2)
    separability = separation / denom if denom > 0 else 0.0

    return dict(
        roc_auc=float(roc_auc), pr_auc=float(pr_auc), accuracy=accuracy,
        precision=prec, recall=rec, f1_score=f1,
        separation=float(separation), separability_index=float(separability),
    )


METRIC_NAMES = ["roc_auc", "pr_auc", "accuracy", "precision", "recall",
                "f1_score", "separation", "separability_index"]


# ---------------------------------------------------------------------------
# Bootstrap
# ---------------------------------------------------------------------------

def bootstrap_marginal(
    pos: np.ndarray, neg: np.ndarray, n_boot: int, rng: np.random.Generator,
) -> Dict[str, np.ndarray]:
    """Independent-samples bootstrap: resample pos and neg separately."""
    n_pos, n_neg = len(pos), len(neg)
    samples: Dict[str, list] = {m: [] for m in METRIC_NAMES}

    for _ in range(n_boot):
        pos_idx = rng.integers(0, n_pos, n_pos)
        neg_idx = rng.integers(0, n_neg, n_neg)
        m = compute_point_metrics(pos[pos_idx], neg[neg_idx])
        for k in METRIC_NAMES:
            samples[k].append(m[k])

    return {k: np.array(v) for k, v in samples.items()}


def bootstrap_paired_delta(
    pos_a: np.ndarray, neg_a: np.ndarray,
    pos_b: np.ndarray, neg_b: np.ndarray,
    n_boot: int, rng: np.random.Generator,
) -> Dict[str, np.ndarray]:
    """Paired bootstrap on (model_a - model_b), resampling the SAME pair
    indices for both models on each iteration (valid only if pos_a/pos_b
    and neg_a/neg_b are index-aligned to the same underlying image pairs).
    """
    n_pos, n_neg = len(pos_a), len(neg_a)
    deltas: Dict[str, list] = {m: [] for m in METRIC_NAMES}

    for _ in range(n_boot):
        pos_idx = rng.integers(0, n_pos, n_pos)
        neg_idx = rng.integers(0, n_neg, n_neg)
        m_a = compute_point_metrics(pos_a[pos_idx], neg_a[neg_idx])
        m_b = compute_point_metrics(pos_b[pos_idx], neg_b[neg_idx])
        for k in METRIC_NAMES:
            deltas[k].append(m_a[k] - m_b[k])

    return {k: np.array(v) for k, v in deltas.items()}


def percentile_ci(samples: np.ndarray, ci: float) -> Tuple[float, float]:
    alpha = (100.0 - ci) / 2.0
    lo = float(np.percentile(samples, alpha))
    hi = float(np.percentile(samples, 100.0 - alpha))
    return lo, hi


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    args = parse_args()
    rng = np.random.default_rng(args.seed)

    v5_path = Path(args.v5_npz)
    base_path = Path(args.base_npz)
    if not v5_path.exists():
        raise FileNotFoundError(
            "Cannot find {}. Point --v5_npz at the saved evaluation_results_v2.npz "
            "for the proposed model (produced by feat_vectest_exhaustive_v2.py)."
            .format(v5_path)
        )
    if not base_path.exists():
        raise FileNotFoundError(
            "Cannot find {}. Point --base_npz at the saved evaluation_results_v2.npz "
            "for the mars-small128 baseline.".format(base_path)
        )

    v5 = np.load(v5_path)
    base = np.load(base_path)

    pos_v5, neg_v5 = v5["positive_scores"], v5["negative_scores"]
    pos_base, neg_base = base["positive_scores"], base["negative_scores"]

    print("[data] V5:       {} positive pairs, {} negative pairs".format(
        len(pos_v5), len(neg_v5)))
    print("[data] Baseline: {} positive pairs, {} negative pairs".format(
        len(pos_base), len(neg_base)))

    paired_ok = (len(pos_v5) == len(pos_base)) and (len(neg_v5) == len(neg_base))
    if not paired_ok:
        print("[WARN] Pair counts differ between V5 and baseline npz files — "
              "falling back to an UNPAIRED delta bootstrap. Verify both were "
              "generated from the same manifest/seed if you expected a paired CI.")

    point_v5 = compute_point_metrics(pos_v5, neg_v5)
    point_base = compute_point_metrics(pos_base, neg_base)

    print("\n[boot] Running {} bootstrap resamples for V5 ...".format(args.n_boot))
    boot_v5 = bootstrap_marginal(pos_v5, neg_v5, args.n_boot, rng)
    print("[boot] Running {} bootstrap resamples for baseline ...".format(args.n_boot))
    boot_base = bootstrap_marginal(pos_base, neg_base, args.n_boot, rng)

    if paired_ok:
        print("[boot] Running {} PAIRED bootstrap resamples for the delta ...".format(
            args.n_boot))
        boot_delta = bootstrap_paired_delta(
            pos_v5, neg_v5, pos_base, neg_base, args.n_boot, rng
        )
        delta_kind = "paired"
    else:
        deltas: Dict[str, list] = {m: [] for m in METRIC_NAMES}
        for i in range(args.n_boot):
            for k in METRIC_NAMES:
                deltas[k].append(boot_v5[k][i % len(boot_v5[k])] -
                                  boot_base[k][i % len(boot_base[k])])
        boot_delta = {k: np.array(v) for k, v in deltas.items()}
        delta_kind = "unpaired (independent resampling)"

    # ---- Report ----
    rows = []
    print("\n" + "=" * 92)
    print("  Bootstrap {:.0f}% CIs  (n_boot={})".format(args.ci, args.n_boot))
    print("=" * 92)
    header = "{:<20}{:>14}{:>22}{:>14}{:>22}".format(
        "Metric", "V5 (point)", "V5 95% CI", "Base (point)", "Base 95% CI")
    print(header)
    print("-" * 92)
    for k in METRIC_NAMES:
        lo_v5, hi_v5 = percentile_ci(boot_v5[k], args.ci)
        lo_b, hi_b = percentile_ci(boot_base[k], args.ci)
        print("{:<20}{:>14.4f}{:>22}{:>14.4f}{:>22}".format(
            k, point_v5[k], "[{:.4f}, {:.4f}]".format(lo_v5, hi_v5),
            point_base[k], "[{:.4f}, {:.4f}]".format(lo_b, hi_b),
        ))
        rows.append(dict(
            metric=k,
            v5_point=point_v5[k], v5_ci_lo=lo_v5, v5_ci_hi=hi_v5,
            base_point=point_base[k], base_ci_lo=lo_b, base_ci_hi=hi_b,
        ))

    print("\n" + "=" * 92)
    print("  Delta (V5 - Baseline), {} bootstrap".format(delta_kind))
    print("=" * 92)
    print("{:<20}{:>14}{:>22}{:>14}".format("Metric", "Delta (point)", "95% CI", "Excludes 0?"))
    print("-" * 92)
    for k in METRIC_NAMES:
        delta_point = point_v5[k] - point_base[k]
        lo_d, hi_d = percentile_ci(boot_delta[k], args.ci)
        excludes_zero = "yes" if (lo_d > 0 or hi_d < 0) else "NO"
        print("{:<20}{:>14.4f}{:>22}{:>14}".format(
            k, delta_point, "[{:.4f}, {:.4f}]".format(lo_d, hi_d), excludes_zero
        ))
        for row in rows:
            if row["metric"] == k:
                row["delta_point"] = delta_point
                row["delta_ci_lo"] = lo_d
                row["delta_ci_hi"] = hi_d
                row["delta_excludes_zero"] = excludes_zero
    print("=" * 92)
    print("\n'Excludes 0?' = NO means the CI on the V5-minus-baseline delta "
          "straddles zero at this bootstrap sample size — report honestly "
          "in the rebuttal if any headline metric shows this.")

    # ---- CSV ----
    out_path = Path(args.output_csv)
    with open(out_path, "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)
    print("\n[save] CSV written -> {}".format(out_path))


if __name__ == "__main__":
    main()
